### ISSUE TITLE
1010: Invalid Transaction: Transaction has a bad signature

### ISSUE THREAD

**Issue by DonCrypto78** [Zondax/ledger-karura#16]
I get this error when trying to sign the transaction: 
1010: Invalid Transaction: Transaction has a bad signature

Using Karura ledger app Version 1.2083.0

:link: [zboto Link](https://app.clickup.com/t/2u49b9f)

**Comment by carlosala** [comment]
Hi! Could we have the transaction information? Pallet, method, arguments, etc.
Thanks!

**Comment by DonCrypto78** [comment]
> Hi! Could we have the transaction information? Pallet, method, arguments, etc. Thanks!

Thank you for fast reply. I'm trying to transfer KAR from https://apps.karura.network/ signing it with Karura ledger app Version 1.2083.0.

Info attached
![1](https://user-images.githubusercontent.com/97727652/181751442-0c8365f3-5486-4db3-a546-916e07b1fa7d.jpg)
![2](https://user-images.githubusercontent.com/97727652/181751451-892e8bbf-a2c9-414a-9918-765a43bccbc2.jpg)

**Comment by carlosala** [comment]
Thanks! It would be helpful if I get the first 4 chars of the address (your one, not the receiver) and the mode that you selected on Crowdloan mode of the app (3rd screen).

**Comment by DonCrypto78** [comment]
> Thanks! It would be helpful if I get the first 4 chars of the address (your one, not the receiver) and the mode that you selected on Crowdloan mode of the app (3rd screen).

Address starts with: sXyB5iew
I tried in legacy mode (screenshots), but also get same error when using "Crowdloan".

**Comment by carlosala** [comment]
I'll test and come back to you as soon as possible👌🏻

**Comment by DonCrypto78** [comment]
Just noticed a new version was released. Does this fix problem explained here?

**Comment by carlosala** [comment]
Hi @DonCrypto78!
I was investigating a bit into that error and I wasn't able to reproduce. I think you are trying to sign a transaction with a Ledger account not matching the one that is installed in the device. Let's check that.
Try to go to https://polkadot.js.org/apps > Accounts > Click the three dots in the account that you are trying to use > Show address on hardware device. Then check if it matches with the one that is written in polkadot-js.

**Comment by DonCrypto78** [comment]
Thank you, and you are correct. The Polkadot.js.org site (and polkadot(js) extension) shows address starting with "15Eh79" while the apps.karura.network wallet shows address starting with "sXyB5i". And it's the sXyB5i address that has the KAR in it.

I tried to add the Karura wallet address (sXyB5i...) with "Add via Ledger" in the [polkadot.js.app](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkarura.polkawallet.io#/accounts), but I dont receive the same address where the KAR is.

Just found that sXyB5i... is a substrate SS58 address for the Polkadot 15Eh79... address.

Do you have any suggestions on how to solve this?

**Comment by carlosala** [comment]
In that case there's not an actual solution for the moment. Karura is a parachain of Kusama, so the derivation paths available to use are the one particular of Karura, and the Kusama one.

**Comment by carlosala** [comment]
How did you add that account to Polkadot-js extension, using which particular app?

**Comment by DonCrypto78** [comment]
The address 15Eh79 was created in Ledger Live then attached to polkadot(js) extension.
Then I connected that address to the Karura network wallet and it apparently became the SS58 address sXyB5i... which is where the KAR was sent and is now stuck.

Polkadot(js) extension
![Skjermbilde 2022-08-08 133210](https://user-images.githubusercontent.com/97727652/183408891-f2e12728-923a-4673-bd51-6d8338964e8a.jpg)

https://apps.karura.network/ - Karura Wallet
![Skjermbilde 2022-08-08 133800](https://user-images.githubusercontent.com/97727652/183409674-bce159bc-2c75-4287-90b0-60b18368b12e.jpg)

.

**Comment by carlosala** [comment]
So, you are using one account derived with the Polkadot path. Could you give me an email? Let's try to solve that, but actually is a big problem. If we manage to solve it, please move all your funds to an account generated by Karura app. You should always use for each chain the appropriate app.

**Comment by DonCrypto78** [comment]
Thank you. My email is stylesheetas@gmail.com

**Comment by carlosala** [comment]
Nice, sent.

**Comment by 777SAW777** [comment]
Hello. I have the same problem. At the beginning of the year, I created polkadot.js.org account for Ledger on the Kusama network. Then, in the application, Karura sent tokens to Ledger. And now I can't sign the transaction(1010: Invalid Transaction: Transaction has a bad signature). Help solve the problem please.

**Comment by carlosala** [comment]
Could you try enabling the `expert mode` and using `Crowdloan` address in `Account` menu?

**Comment by 777SAW777** [comment]
> Could you try enabling the `expert mode` and using `Crowdloan` address in `Account` menu?

You are my savior friend!♥ Thank you so much. Let me send you a KSM as a token of gratitude.
Can I leave this feature enabled (Crowdloan)?

**Comment by carlosala** [comment]
That's our job! I'm glad I could help☺️
And, yes! If you don't change anything, that feature is going to be enabled forever!

**Comment by 777SAW777** [comment]
> That's our job! I'm glad I could help☺️ And, yes! If you don't change anything, that feature is going to be enabled forever!

Thank you sir! I've been waiting for this for almost a year.🙂
