### ISSUE TITLE
Now I can't sign the transaction (1010: Invalid transaction: The transaction has an invalid signature)

### ISSUE THREAD

**Issue by 777SAW777** [Zondax/ledger-karura#19]
Hello. I have a problem. At the beginning of the year, I created a polkadot.js account for Ledger on the Kusama network. Then, in the app, Karura sent the tokens to the Ledger. And now I can't sign the transaction (1010: Invalid transaction: The transaction has an invalid signature). Help solve the problem please.

:link: [zboto Link](https://app.clickup.com/t/35zqrm2)

**Comment by carlosala** [comment]
Hi @777SAW777!
I answered to you here https://github.com/Zondax/ledger-karura/issues/16#issuecomment-1311524800
