### ISSUE TITLE
Ledger app looks outdated

### ISSUE THREAD

**Issue by remi-parain** [Zondax/ledger-karura#25]
Hi !
this morning i wasn't able to bridge Kusama to Karura, i was facing Ledger: Txn version not supported at the ledger signature.
according to https://support.polkadot.network/support/solutions/articles/65000176738-ledger-txn-version-not-supported, it mean the ledger app is outdated.
after updating the Kusama ledger app to latest , it worked.

Now, on Karura network, using the ledger-karura app , i'm facing the same error Ledger: Txn version not supported for any action (staking / swapping,etc.. ).
My guess is the app need to be updated. but there is no updates available in ledger live.
Is there a bug or anything i can do or just have to wait for ledger to publish the app ? if so, how long could it take ? hours ? days ?
Thanks you in advance

:link: [zboto Link](https://app.clickup.com/t/8676ynb9t)

**Comment by carlosala** [comment]
Hi! There's a new release of the app [here](https://github.com/Zondax/ledger-karura/releases/tag/v2.2110.0) but Ledger didn't publish it yet. You can install the latest version using the installer we provide (only available for nanoS and nanoSP).
Usually, it takes some time until Ledger releases the app, I can't give you a precise ETA. Sorry for the inconvenience, and thanks for your report!
